M48
; DRILL file {KiCad 7.0.6} date Thu Feb  6 17:31:14 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-06T17:31:14+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.9285Y-2.7417
X5.1195Y-2.7417
T2
X4.9167Y-2.6224
X5.1313Y-2.6224
T0
M30
